name: Binderbot
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
    paths:
      - '**.ipynb'
  pull_request:
    branches:
      - master
    paths:
      - '**.ipynb'

env:
  BINDER_URL: "http://mybinder.org"
  BINDER_REPO: "binder-examples/requirements"
  BINDER_REF: master
  BINDERBOT_TARGET_BRANCH: binderbot-built
  GALLERY_REPOSITORY: "pangeo-gallery/pangeo-gallery"

jobs:
  build:
    name: Binderbot Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install Binderbot from github master
        run: pip install git+https://github.com/pangeo-gallery/binderbot.git
      - name: Build notebooks using Binderbot
        run: |
          git checkout -b binderbot-new
          python -m binderbot.cli \
          --binder-url "$BINDER_URL" \
          --repo "$BINDER_REPO" \
          --ref "$BINDER_REF" \
          *.ipynb
      - name: Commit files
        if: github.ref == 'refs/heads/master'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Binderbot output" -a
          git checkout --track origin/binderbot-built
          git merge -s ours binderbot-new
      - name: Push commit
        if: github.ref == 'refs/heads/master'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BINDERBOT_TARGET_BRANCH }}
          force: true
      - name: Trigger repository dispatch on Pangeo Gallery
        if: github.ref == 'refs/heads/master'
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: ${{ env.GALLERY_REPOSITORY }}
          token: ${{ secrets.REPO_DISPATCH_TOKEN }}
          event-type: update-gallery
          client-payload: '{"repo": "${{ github.repository }}", "branch": "${{ env.BINDERBOT_TARGET_BRANCH }}", "sha": "${{ github.sha }}"}'
