name: Test YAML Parser
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: parse config
        id: parse
        uses: CumulusDS/get-yaml-paths-action@v0.0.3
        with:
          file: file.yaml
          bar: foo.bar
          providerStage: provider.stage
      - name: show outputs
        run: echo bar: ${{ steps.parse.outputs.bar }}
